### ISSUE TITLE
Crash when opening menu

### ISSUE THREAD

**Issue by delthas** [plusCubed/matlog#47]
When clicking the menu button in the app, the app crashes.
Logs:
```
Exception while inflating <vector>
android.content.res.Resources$NotFoundException: Resource is not a ColorStateList (color or path): TypedValue{t=0x2/d=0x1010429 a=-1}
	at android.content.res.Resources.loadColorStateList(Resources.java:2376)
	at android.content.res.TypedArray.getColorStateList(TypedArray.java:343)
	at android.support.graphics.drawable.VectorDrawableCompat.inflate(VectorDrawableCompat.java:5757)
	at android.support.graphics.drawable.VectorDrawableCompat.createFromXmlInner(VectorDrawableCompat.java:674)
	at android.support.v7.widget.AppCompatDrawableManager$VdcInflateDelegate.createFromXmlInner(AppCompatDrawableManager.java:775)
	at android.support.v7.widget.AppCompatDrawableManager.loadDrawableFromDelegates(AppCompatDrawableManager.java:366)
	at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:198)
	at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:191)
	at android.support.v7.content.res.AppCompatResources.getDrawable(AppCompatResources.java:102)
	at android.support.v7.view.menu.MenuItemImpl.getIcon(MenuItemImpl.java:505)
	at android.support.v7.view.menu.ListMenuItemView.initialize$667f453d(ListMenuItemView.java:134)
	at android.support.v7.view.menu.MenuAdapter.getView(MenuAdapter.java:109)
	at android.support.v7.view.menu.MenuPopup.measureIndividualMenuWidth(MenuPopup.java:161)
	at android.support.v7.view.menu.StandardMenuPopup.show(StandardMenuPopup.java:2174)
	at android.support.v7.view.menu.MenuPopupHelper.showPopup(MenuPopupHelper.java:290)
	at android.support.v7.view.menu.MenuPopupHelper.tryShow(MenuPopupHelper.java:177)
	at android.support.v7.widget.ActionMenuPresenter$OpenOverflowRunnable.run(ActionMenuPresenter.java:806)
	at android.os.Handler.handleCallback(Handler.java:733)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5146)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:732)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:566)
	at dalvik.system.NativeStart.main(Native Method)

FATAL EXCEPTION: main
Process: com.pluscubed.matloglibre, PID: 22628
android.content.res.Resources$NotFoundException: File res/drawable/ic_share_white_24dp.xml from drawable resource ID #0x7f080075. If the resource you are trying to use is a vector resource, you may be referencing it in an unsupported way. See AppCompatDelegate.setCompatVectorFromResourcesEnabled() for more info.
	at android.content.res.Resources.loadDrawable(Resources.java:2235)
	at android.content.res.Resources.getDrawable(Resources.java:733)
	at android.content.res.Resources.getDrawable(Resources.java:711)
	at android.support.v7.widget.VectorEnabledTintResources.superGetDrawable(VectorEnabledTintResources.java:75)
	at android.support.v7.widget.AppCompatDrawableManager.onDrawableLoadedFromResources(AppCompatDrawableManager.java:432)
	at android.support.v7.widget.VectorEnabledTintResources.getDrawable(VectorEnabledTintResources.java:68)
	at android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:465)
	at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:203)
	at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:191)
	at android.support.v7.content.res.AppCompatResources.getDrawable(AppCompatResources.java:102)
	at android.support.v7.view.menu.MenuItemImpl.getIcon(MenuItemImpl.java:505)
	at android.support.v7.view.menu.ListMenuItemView.initialize$667f453d(ListMenuItemView.java:134)
	at android.support.v7.view.menu.MenuAdapter.getView(MenuAdapter.java:109)
	at android.support.v7.view.menu.MenuPopup.measureIndividualMenuWidth(MenuPopup.java:161)
	at android.support.v7.view.menu.StandardMenuPopup.show(StandardMenuPopup.java:2174)
	at android.support.v7.view.menu.MenuPopupHelper.showPopup(MenuPopupHelper.java:290)
	at android.support.v7.view.menu.MenuPopupHelper.tryShow(MenuPopupHelper.java:177)
	at android.support.v7.widget.ActionMenuPresenter$OpenOverflowRunnable.run(ActionMenuPresenter.java:806)
	at android.os.Handler.handleCallback(Handler.java:733)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5146)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:732)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:566)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #16: invalid drawable tag vector
	at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:933)
	at android.graphics.drawable.Drawable.createFromXml(Drawable.java:877)
	at android.content.res.Resources.loadDrawable(Resources.java:2231)
	... 26 more
```

**Comment by plusCubed** [comment]
Hmm... looks like something changed with `AppCompatDelegate.setCompatVectorFromResourcesEnabled(true)`, at least for menu icons, so MatLog crashes on 4.x devices.

**Comment by plusCubed** [comment]
Never mind, it was due to a color state list being used when it shouldn't be. Fixed. Thanks for reporting!
