### ISSUE TITLE
Fail to Grant READ_LOGS via ADB

### ISSUE THREAD

**Issue by LuisCarlosHK** [plusCubed/matlog#64]
I tried to grant permission via adb and get the following error.

Exception occurred while executing 'grant':
java.lang.SecurityException: grantRuntimePermission: Neither user 2000 nor current process has android.permission.GRANT_RUNTIME_PERMISSIONS.
at android.app.ContextImpl.enforce(ContextImpl.java:2187)
at android.app.ContextImpl.enforceCallingOrSelfPermission(ContextImpl.java:2215)
at com.android.server.pm.permission.PermissionManagerService.grantRuntimePermissionInternal(PermissionManagerService.java:1481)
at com.android.server.pm.permission.PermissionManagerService.grantRuntimePermission(PermissionManagerService.java:1463)
at android.permission.PermissionManager.grantRuntimePermission(PermissionManager.java:378)
at com.android.server.pm.PackageManagerShellCommand.runGrantRevokePermission(PackageManagerShellCommand.java:2419)
at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:260)
at com.android.modules.utils.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:97)
at android.os.ShellCommand.exec(ShellCommand.java:38)
at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:26028)
at android.os.Binder.shellCommand(Binder.java:972)
at android.os.Binder.onTransact(Binder.java:856)
at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:4818)
at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:9350)
at android.os.Binder.execTransactInternal(Binder.java:1228)
at android.os.Binder.execTransact(Binder.java:1165)

**Comment by ruzanow** [comment]
On Android 10+ you need to enable the option called “Disable Permission Monitoring” (scroll down in the developer options). 
I needed to reboot my phone.

**Comment by LuisCarlosHK** [comment]
It works. Thank you.

**Comment by Luisdeugarza** [comment]
> On Android 10+ you need to enable the option called “Disable Permission Monitoring” (scroll down in the developer options). I needed to reboot my phone.

where is that option? i dont find it in my xiaomi
